### ISSUE TITLE
Translating enzyme back to ursgal_style does not work

### ISSUE THREAD

**Issue by MKoesters** [uparma/uparma-lib#5]
Problem
========

When trying to translate the value of `enzyme` from `msfragger_style_1` to `ursgal_style_1`, the translation does not work as I'd suspect it to work.

Reproduce
=========

```
>>> param_mapper.translate({'enzyme": "'KR;C;P"},"msfragger_style_3","ursgal_style_1",)
{'enzyme': {'original_key': 'enzyme',
            'original_style': 'msfragger_style_3',
            'original_value': 'KR;C;P',
            'translated_key': 'enzyme',
            'translated_style': 'ursgal_style_1',
            'translated_value': 'KR;C;P',
            'was_translated': True}}
```

Expected output
==============

I'd expect the `ursgal_style_1` translation to be `trypsin` as this is the ursgal value

https://github.com/uparma/uparma-lib/blob/183a0ca13b032b5f78df164c0f6b90d0f12a2064/jsons/parameters.json#L2804-L2809

**Comment by fu** [comment]
probably not the only UParma entry that is missing the ursgal_style_1 value translation, what do you think @MKoesters ?

**Comment by MKoesters** [comment]
I'll create an Issue, check all the parameters and try to add a script which adds the missing ursgal_style translations
